### ISSUE TITLE
Handle daylight navigation bar

### ISSUE THREAD

**Issue by awikkerink** [Brightspace/react-valence-ui-iframe#8]
Each iframe has a navbar of its own. The monolith has d2l_navbar, ASV uses a NavBar component, and daylight has d2l-navigation-ui component

We need a universal method of eliminating "navinception" that will work with the monolith, daylight, and FRAs.

**Comment by Surekh** [comment]
Fixed in #10 ? @awikkerink

**Comment by awikkerink** [comment]
Yes
